# Generated by Django 3.1.2 on 2021-04-19 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('OS_version', models.CharField(max_length=50)),
                ('RAM', models.IntegerField()),
                ('internal_memory_capacity', models.IntegerField()),
                ('ppi', models.IntegerField()),
                ('processor', models.CharField(max_length=50)),
                ('image_size', models.CharField(max_length=50)),
                ('number_cameras', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Phone',
                'verbose_name_plural': 'Phones',
            },
        ),
        migrations.CreateModel(
            name='Xiaomi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality_price', models.CharField(max_length=50)),
                ('phone_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='phones.phone')),
            ],
            options={
                'verbose_name': 'Xiaomi',
                'verbose_name_plural': 'Xiaomi',
            },
        ),
        migrations.CreateModel(
            name='Samsung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_android', models.CharField(max_length=50)),
                ('phone_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='phones.phone')),
            ],
            options={
                'verbose_name': 'Samsung',
                'verbose_name_plural': 'Samsung',
            },
        ),
        migrations.CreateModel(
            name='Apple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optimization', models.CharField(max_length=50)),
                ('phone_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='phones.phone')),
            ],
            options={
                'verbose_name': 'Apple',
                'verbose_name_plural': 'Apple',
            },
        ),
    ]
